apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.redis.name }}-pv
  labels:
    app: {{ .Values.redis.labels.app }}

spec:
  capacity:
    storage: {{ .Values.redis.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.redis.persistence.reclaimPolicy }}
  storageClassName: {{ .Values.redis.persistence.storageClassName }}
  hostPath:                          # ⚠️ À remplacer par NFS/cloud en prod
    path: {{ .Values.redis.persistence.hostPath }}