apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.redis.service.name }}
    labels:
        app: {{ .Values.redis.service.name }}
spec:
    selector:
        app: {{ .Values.redis.labels.app }}
    ports:
      - name: redis-http
        protocol: TCP
        port: 80
        targetPort: 6379
        
      - name: redis-ssl
        protocol: TCP
        port: 443
        targetPort: 6379
    type: {{ .Values.redis.service.type }}
