apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespaces.app }}
  annotations:
    kubernetes.io/ingress.class: "nginx"

spec:
  ingressClassName: nginx

  rules:
    - host: {{ .Values.frontend.ingress.host }}
      http:
        paths:
          - path: {{ .Values.frontend.ingress.prefix }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.service.name }}
                port:
                  number: {{ .Values.frontend.service.port }}

    - host: {{ .Values.backend.ingress.host }}
      http:
        paths:
          - path: {{ .Values.backend.ingress.prefix }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.service.name }}
                port:
                  number: {{ .Values.backend.service.port }}