services:
  postgres:
    image: postgres:16-alpine
    container_name: dream_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: "trust"

    ports:
      - "5434:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dream_network
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6380:6379"
    networks:
      - dream_network
    command: redis-server --appendonly yes
    volumes:
    - redis_data:/data


  api:
    build: .
    container_name: feoSync_api
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - dream_network

volumes:
  postgres_data:
  redis_data:

networks:
  dream_network:
    driver: bridge
