"""init

Revision ID: 71910f704f0b
Revises: 
Create Date: 2026-03-13 10:44:22.789543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71910f704f0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('features', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('google_email', sa.String(length=255), nullable=True),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('organisations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('tone', sa.Enum('formal', 'informal', 'friendly', 'professional', 'casual', name='toneenum', native_enum=False), nullable=False),
    sa.Column('sector', sa.Enum('technology', 'finance', 'healthcare', 'education', 'retail', 'manufacturing', name='sectorenum', native_enum=False), nullable=False),
    sa.Column('brand_color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('refresh_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_hased', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hased')
    )
    op.create_table('ai_generation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_used', sa.String(length=255), nullable=False),
    sa.Column('output_data', sa.String(length=255), nullable=False),
    sa.Column('model_used', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('token_used', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facebook_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.String(length=255), nullable=False),
    sa.Column('page_name', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id')
    )
    op.create_table('post_template',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('asset_url', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.Enum('technology', 'finance', 'healthcare', 'education', 'retail', 'manufacturing', name='sectorenum'), nullable=False),
    sa.Column('usage_acount', sa.Integer(), nullable=False),
    sa.Column('is_template_app', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whatsapp',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('waba_id', sa.String(length=255), nullable=False),
    sa.Column('broadcast_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('page_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fb_page_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fans_totals', sa.Integer(), nullable=False),
    sa.Column('impressions_unique', sa.Integer(), nullable=False),
    sa.Column('engaged_users', sa.Integer(), nullable=False),
    sa.Column('new_followers', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fb_page_id'], ['facebook_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('post_template_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cron_expression', sa.String(), nullable=False),
    sa.Column('data_source_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['post_template_id'], ['post_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_post',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caption', sa.String(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('publish_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'PUBLISHED', 'FAILED', name='post_status'), nullable=False),
    sa.Column('chanels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('page_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('post_template_id', sa.Uuid(), nullable=True),
    sa.Column('ai_generation_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['ai_generation_id'], ['ai_generation.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['post_template_id'], ['post_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('published_post',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scheduled_post_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=True),
    sa.Column('chanel', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initial_reach', sa.Integer(), nullable=True),
    sa.Column('initial_impressions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scheduled_post_id'], ['scheduled_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_analitycs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('published_post_id', sa.UUID(), nullable=False),
    sa.Column('mesured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('reactions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['published_post_id'], ['published_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_analitycs')
    op.drop_table('published_post')
    op.drop_table('scheduled_post')
    op.drop_table('schedule')
    op.drop_table('page_insights')
    op.drop_table('whatsapp')
    op.drop_table('post_template')
    op.drop_table('facebook_pages')
    op.drop_table('ai_generation')
    op.drop_table('refresh_token')
    op.drop_table('organisations')
    op.drop_table('users')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
