"""test

Revision ID: a7b95a55a679
Revises: 71910f704f0b
Create Date: 2026-03-14 11:18:50.791859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7b95a55a679'
down_revision: Union[str, Sequence[str], None] = '71910f704f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE published_post CASCADE")
    op.execute("DROP TABLE post_analitycs CASCADE")
    op.add_column('facebook_pages', sa.Column('fb_page_id', sa.String(length=255), nullable=False))
    op.add_column('facebook_pages', sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('facebook_pages', sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('facebook_pages', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('facebook_pages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('facebook_pages', 'access_token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_constraint(op.f('facebook_pages_page_id_key'), 'facebook_pages', type_='unique')
    op.create_unique_constraint(None, 'facebook_pages', ['fb_page_id'])
    op.drop_column('facebook_pages', 'page_id')
    op.drop_column('facebook_pages', 'token_expiry')
    op.drop_column('facebook_pages', 'last_synced')
    op.add_column('page_insights', sa.Column('fans_total', sa.Integer(), nullable=False))
    op.add_column('page_insights', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('page_insights', 'fans_totals')
    op.add_column('plans', sa.Column('max_page', sa.Integer(), nullable=False))
    op.add_column('plans', sa.Column('max_post_month', sa.Integer(), nullable=False))
    op.add_column('plans', sa.Column('max_ai_gen', sa.Integer(), nullable=False))
    op.drop_column('plans', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('plans', 'max_ai_gen')
    op.drop_column('plans', 'max_post_month')
    op.drop_column('plans', 'max_page')
    op.add_column('page_insights', sa.Column('fans_totals', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('page_insights', 'created_at')
    op.drop_column('page_insights', 'fans_total')
    op.add_column('facebook_pages', sa.Column('last_synced', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('facebook_pages', sa.Column('token_expiry', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('facebook_pages', sa.Column('page_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'facebook_pages', type_='unique')
    op.create_unique_constraint(op.f('facebook_pages_page_id_key'), 'facebook_pages', ['page_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('facebook_pages', 'access_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('facebook_pages', 'updated_at')
    op.drop_column('facebook_pages', 'created_at')
    op.drop_column('facebook_pages', 'last_sync_at')
    op.drop_column('facebook_pages', 'token_expires_at')
    op.drop_column('facebook_pages', 'fb_page_id')
    op.create_table('post_analitycs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('published_post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('mesured_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('reach', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('impressions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reactions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('comments', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shares', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clicks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['published_post_id'], ['published_post.id'], name=op.f('post_analitycs_published_post_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('post_analitycs_pkey'))
    )
    op.create_table('published_post',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scheduled_post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('chanel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('initial_reach', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('initial_impressions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scheduled_post_id'], ['scheduled_post.id'], name=op.f('published_post_scheduled_post_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('published_post_pkey'))
    )
    # ### end Alembic commands ###
