global:
  env: base

namespaces:
  app: feosync-app
  data: feosync-data
  infra: feosync-infra

frontend:
  name: feosync-client
  namespace: feosync-app
  labels:
    app: feosync-client

  image:
    repository: nandrainadev/feosync-client
    tag: latest
    pullPolicy: IfNotPresent

  containerPort: 3000
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 250m

  service:
    name: feosync-client-service
    port: 80
    targetPort: 3000
    type: NodePort

  ingress:
    host: app.feosync.com
    prefix: /

# ================================================================================================

backend:
  name: feosync-server
  namespace: feosync-app

  labels:
    app: feosync-server
  readinessProbe:
    path: /

  image:
    repository: nandrainadev/feosync-server
    tag: latest
    pullPolicy: IfNotPresent

  containerPort: 8000

  autoscaling:
    name: feosync-server-hpa
    labels:
      app: feosync-server-hpa
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 250m

  service:
    name: feosync-server-service
    port: 80
    targetPort: 8000
    type: NodePort

  ingress:
    host: api.feosync.com
    prefix: /

# ================================================================================================

postgres:
  name: feosync-db
  namespace: feosync-data
  instances: 1
  storage: 5Gi
  database: feosync_db
  user: feosync_owner
  secretName: feosync-db-secret
  storageClass: standard

pgbouncer:
  namespace: feosync-data
  instances: 1
  poolMode: session
  maxClientConn: "500"
  defaultPoolSize: "50"

# ================================================================================================

redis_operator:
  name: feosync-redis-operator
  namespace: feosync-infra
  enabled: true
  replicaCount: 1
  redisOperator:
    image:
      repository: ghcr.io/ot-container-kit/redis-operator/redis-operator
      tag: "v0.24.0"
      pullPolicy: IfNotPresent
  persistence:
    size: 1Gi
    storageClassName: standard

# ================================================================================================

cloudnative-pg:
  namespace: feosync-data
  crds:
    create: false