name: FEOSYNC CD

on:
    workflow_run:
        workflows: ["FEOSYNC CI"]
        types:
            - completed
jobs:
    deploy:
        runs-on: self-hosted
        environment: env
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - name: starting deploy
              run: echo "Starting deploy"