name: feosync client cd

on:
    workflow_run:
        workflows: ["feosync client ci"]
        types:
            - completed
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: env
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - name: starting deploy
              run: echo "Starting deploy"