name: FEOSYNC CI
permissions:
  contents: write
  discussions: write
on:
  push:
    branches: [prod]
  pull_request:
    branches: [prod]
jobs:
      build:
        runs-on: ubuntu-latest
        environment: env

        steps:
          - name: starting build
            run: echo "Starting build"